import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function GET() {
  try {
    // Email configuration - same as contact form
    const emailConfig = {
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT) || 587,
      secure: false, // Use TLS
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
      tls: {
        rejectUnauthorized: false
      }
    };

    console.log('Testing contact form email with config:', {
      host: emailConfig.host,
      port: emailConfig.port,
      user: emailConfig.auth.user,
      // Don't log password for security
    });

    const transporter = nodemailer.createTransport(emailConfig);

    // Verify connection
    await transporter.verify();

    // Test contact form data
    const testContactData = {
      name: 'John Doe',
      email: 'test@example.com',
      phone: '+974 5555 1234',
      company: 'Test Company Ltd.',
      service: 'Facility Maintenance',
      message: 'This is a test message from the contact form email system. Please ignore this test submission.'
    };

    const contactId = `CT${Date.now()}TEST`;

    // Send test contact email
    const testEmailHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>TEST - Contact Form Email - ${contactId}</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #dc2626, #b91c1c); color: white; padding: 20px; text-align: center; }
          .test-notice { background: #fef3c7; border: 2px solid #f59e0b; padding: 15px; margin: 10px 0; border-radius: 5px; text-align: center; }
          .content { background: #f9f9f9; padding: 20px; }
          .contact-details { background: white; padding: 15px; margin: 10px 0; border-radius: 5px; }
          .label { font-weight: bold; color: #dc2626; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🧪 TEST - Contact Form Email</h1>
            <p>Contact ID: ${contactId}</p>
          </div>
          
          <div class="test-notice">
            <h2>⚠️ THIS IS A TEST EMAIL ⚠️</h2>
            <p>This email was generated by the contact form test system. Please ignore this submission.</p>
          </div>
          
          <div class="content">
            <div class="contact-details">
              <h2>Test Contact Information</h2>
              <p><span class="label">Name:</span> ${testContactData.name}</p>
              <p><span class="label">Email:</span> ${testContactData.email}</p>
              <p><span class="label">Phone:</span> ${testContactData.phone}</p>
              <p><span class="label">Company:</span> ${testContactData.company}</p>
              <p><span class="label">Service Interest:</span> ${testContactData.service}</p>
            </div>

            <div class="contact-details">
              <h2>Test Message</h2>
              <div style="background: white; padding: 15px; border-radius: 5px; white-space: pre-wrap;">${testContactData.message}</div>
            </div>

            <div class="contact-details">
              <h2>✅ Email System Status</h2>
              <ul>
                <li>✅ SMTP Connection: Working</li>
                <li>✅ Email Template: Rendering correctly</li>
                <li>✅ Contact Form API: Functional</li>
                <li>✅ Email Delivery: Successful</li>
              </ul>
            </div>
          </div>

          <div style="text-align: center; padding: 20px; color: #666;">
            <p>Test email sent at: ${new Date().toLocaleString()}</p>
            <p><strong>Contact form email system is working correctly!</strong></p>
          </div>
        </div>
      </body>
      </html>
    `;

    const testMailOptions = {
      from: process.env.SMTP_USER,
      to: 'fms@fabtechqatar.com',
      subject: `🧪 TEST - Contact Form Email System - ${contactId}`,
      html: testEmailHtml,
    };

    const result = await transporter.sendMail(testMailOptions);

    return NextResponse.json({
      success: true,
      message: 'Contact form email test completed successfully!',
      messageId: result.messageId,
      contactId: contactId,
      timestamp: new Date().toISOString(),
      testData: testContactData
    });

  } catch (error) {
    console.error('Contact form email test error:', error);
    return NextResponse.json({
      success: false,
      error: 'Contact form email test failed',
      details: error.message,
      timestamp: new Date().toISOString()
    }, { status: 500 });
  }
}

